version: '3.8'
services:
  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci && node server/index.js"
    ports:
      - '3000:3000'
    env_file:
      - .env
  vite:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - '5173:5173'
    env_file:
      - .env
    depends_on:
      - api
volumes:
  node_modules:
